# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 20, 20, 25, 59, 514172)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
